say_title ( c_locale ( 2090 ) ) 
say ( c_locale ( 2192 ) ) 
local b = select ( c_locale ( 10928 ) , c_locale ( 10929 ) ) 
if 1 == b then 
if pc . get_money ( ) >= 100000 then 
pc . changemoney ( - 100000 ) 
say_title ( c_locale ( 114 ) ) 
say ( c_locale ( 2193 ) ) 
pc . give_item2 ( 50053 , 1 ) 
else 
say_title ( c_locale ( 2090 ) ) 
say ( c_locale ( 2219 ) ) 
end 
elseif 2 == b then return 
else 
say ( c_locale ( 1298 , b ) ) 
end 
