local t = marriage . get_wedding_list ( ) 
if table . getn ( t ) == 0 then 
say_title ( c_locale ( 689 ) ) 
say ( c_locale ( 6494 ) ) 
else 
local wedding_names = { } 
table . foreachi ( t , function ( n , p ) wedding_names [ n ] = c_locale ( 6495 , p [ 3 ] , p [ 4 ] ) end ) 
wedding_names [ table . getn ( t ) + 1 ] = c_locale ( 2454 ) 
local s = select_table ( wedding_names ) 
if s ~= table . getn ( wedding_names ) then 
marriage . join_wedding ( t [ s ] [ 1 ] , t [ s ] [ 2 ] ) 
end 
end 
