if not party . is_party ( ) then 
say_title ( c_locale ( 883 ) ) 
say ( c_locale ( 885 ) ) 
return 
end 
if not party . is_leader ( ) then 
say_title ( c_locale ( 883 ) ) 
say ( c_locale ( 880 ) ) 
return 
end 
say_title ( c_locale ( 883 ) ) 
say ( c_locale ( 892 ) ) 
if select ( c_locale ( 878 ) , c_locale ( 879 ) ) == 1 then 
blue_dragon_lair . clear_server_timers ( ) 
blue_dragon_lair . clear_dungeon ( d . get_map_index ( ) ) 
end 
