local empire = pc . get_empire ( ) 
if empire == 1 then 
a = select ( c_locale ( 1580 ) , c_locale ( 1581 ) , c_locale ( 1582 ) , c_locale ( 2426 ) ) 
if 1 == a then 
say ( c_locale ( 1583 ) ) 
wait ( ) 
pc . warp ( 975200 , 133000 ) 
elseif 2 == a then 
say ( c_locale ( 1584 ) ) 
wait ( ) 
pc . warp ( 978000 , 199500 ) 
elseif 3 == a then 
say ( c_locale ( 1585 ) ) 
wait ( ) 
pc . warp ( 967900 , 199400 ) 
else 
return 
end 
else 
say ( c_locale ( 1586 ) ) 
end 
