if get_global_time ( ) - pc . getqf ( "last_reindeer_give_time" ) < 86400 then 
say_title ( c_mob_name ( 20126 ) ) 
say ( c_locale ( 6714 ) ) 
else 
say_title ( c_mob_name ( 20126 ) ) 
say ( c_locale ( 6709 ) ) 
wait ( ) 
say_title ( c_mob_name ( 20126 ) ) 
say ( c_locale ( 11788 ) ) 
pc . give_item2_select ( 53007 , 1 ) 
item . set_socket ( 0 , get_global_time ( ) + 7200 ) 
pc . setqf ( "last_reindeer_give_time" , get_global_time ( ) ) 
end 
