local empire = pc . get_empire ( ) 
if empire == 3 then 
a = select ( c_locale ( 1580 ) , c_locale ( 1581 ) , c_locale ( 1582 ) , c_locale ( 2426 ) ) 
if 1 == a then 
say ( c_locale ( 1588 ) ) 
wait ( ) 
pc . warp ( 1.0189e+06 , 148400 ) 
elseif 2 == a then 
say ( c_locale ( 1577 ) ) 
wait ( ) 
pc . warp ( 1.019e+06 , 200200 ) 
elseif 3 == a then 
say ( c_locale ( 1585 ) ) 
wait ( ) 
pc . warp ( 923900 , 183600 ) 
else 
return 
end 
else 
say ( c_locale ( 1579 ) ) 
end 
