local setting = crack_snow_dungeon . setting ( ) 
if not party . is_leader ( ) then 
say ( c_locale ( 11292 ) ) 
return 
end 
say ( c_locale ( 11467 ) ) 
if select ( c_locale ( 11468 ) , c_locale ( 11469 ) ) == 1 then 
npc . purge ( ) 
crack_snow_dungeon . clear_level ( d . get_map_index ( ) ) 
d . notice ( c_locale ( 11444 ) ) 
server_timer ( "crack_snow_dungeon_floor10_timer" , setting . floor_jump_time , d . get_map_index ( ) ) 
end 
